# This file contains values from Cookiecutter

default_context:
  project_name: "pdfparser"
  project_description: "A simple pdf parser for parsing KTU Result PDF to json"
  organization: "pdfparser"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "0x006e"
  email: "nithin486@hotmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
