name: Python Package

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: python setup.py sdist bdist_wheel

      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: wheel-package
          path: dist/*.whl
